model dsmodelIterationSelect
  extends NHES.Electrolysis.Electrolyzers.SOEC_Examples_AS.HTSEFinal_SEC;
  annotation(__Dymola_SimulationIterationVariables={"HTSE.SOEC.CathodeIn.m_flow",
   "HTSE.FuelHX.volume_2[20].medium.X[1]", "HTSE.SOEC.CathodeVolume.medium.X[1]",
   "HTSE.FuelHX.volume_2[20].medium.X[2]", "HTSE.SOEC.CathodeVolume.medium.X[2]",
   "HTSE.FuelHX.volume_1[1].medium.X[1]", "HTSE.FuelHX.volume_1[1].medium.X[2]",
   "HTSE.FuelHX.volume_2[20].mXi[2]", "HTSE.FuelHX.volume_2[20].mXi[1]", 
  "HTSE.FuelHX.volume_2[20].U", "HTSE.FuelHX.volume_2[20].m", "HTSE.FuelHX.volume_2[20].medium.p",
   "HTSE.FuelHX.volume_2[20].medium.T", "HTSE.FuelHX.volume_1[1].mXi[2]", 
  "HTSE.FuelHX.volume_1[1].mXi[1]", "HTSE.FuelHX.volume_1[1].U", 
  "HTSE.FuelHX.volume_1[1].m", "HTSE.SOEC.CathodeVolume.mXi[2]", 
  "HTSE.SOEC.CathodeVolume.mXi[1]", "HTSE.SOEC.CathodeVolume.U", 
  "HTSE.SOEC.CathodeVolume.m", "HTSE.FuelTH.medium.p", "HTSE.SOEC.CathodeVolume.medium.T",
   "HTSE.FuelTH.medium.Xi[1]", "HTSE.FuelTH.medium.Xi[2]", "HTSE.FuelHX.volume_1[1].medium.T",
   "HTSE.FuelTH.port_a.h_outflow", "der(HTSE.SOEC.CathodeVolume.medium.T)", 
  "der(HTSE.FuelHX.volume_1[1].medium.T)", "HTSE.SOEC.CathodeOut.m_flow", 
  "der(HTSE.FuelTH.medium.p)", "der(HTSE.SOEC.CathodeVolume.medium.X[2])", 
  "der(HTSE.SOEC.CathodeVolume.medium.X[1])", "der(HTSE.FuelHX.volume_1[1].medium.X[2])",
   "der(HTSE.FuelHX.volume_1[1].medium.X[1])", "HTSE.SOEC.AnodeIn.m_flow", 
  "HTSE.AirHX.volume_2[20].medium.X[1]", "HTSE.SOEC.AnodeVolume.medium.X[1]", 
  "HTSE.AirHX.volume_2[20].medium.X[2]", "HTSE.SOEC.AnodeVolume.medium.X[2]", 
  "HTSE.AirHX.volume_1[1].medium.X[1]", "HTSE.AirHX.volume_1[1].medium.X[2]", 
  "HTSE.AirHX.volume_2[20].mXi[2]", "HTSE.AirHX.volume_2[20].mXi[1]", 
  "HTSE.AirHX.volume_2[20].U", "HTSE.AirHX.volume_2[20].m", "HTSE.AirHX.volume_2[20].medium.p",
   "HTSE.AirHX.volume_2[20].medium.T", "HTSE.AirHX.volume_1[1].mXi[2]", 
  "HTSE.AirHX.volume_1[1].mXi[1]", "HTSE.AirHX.volume_1[1].U", "HTSE.AirHX.volume_1[1].m",
   "HTSE.SOEC.AnodeVolume.mXi[2]", "HTSE.SOEC.AnodeVolume.mXi[1]", 
  "HTSE.SOEC.AnodeVolume.U", "HTSE.SOEC.AnodeVolume.m", "HTSE.AirTH.medium.p", 
  "HTSE.SOEC.AnodeVolume.medium.T", "HTSE.AirTH.medium.Xi[1]", "HTSE.AirTH.medium.Xi[2]",
   "HTSE.AirHX.volume_1[1].medium.T", "HTSE.AirTH.port_a.h_outflow", 
  "der(HTSE.SOEC.AnodeVolume.medium.T)", "der(HTSE.AirHX.volume_1[1].medium.T)",
   "HTSE.SOEC.AnodeOut.m_flow", "der(HTSE.AirTH.medium.p)", "der(HTSE.SOEC.AnodeVolume.medium.X[2])",
   "der(HTSE.SOEC.AnodeVolume.medium.X[1])", "der(HTSE.AirHX.volume_1[1].medium.X[2])",
   "der(HTSE.AirHX.volume_1[1].medium.X[1])", "der(HTSE.condenser.medium.X[1])",
   "der(HTSE.condenser.medium.X[2])", "HTSE.X_H1.XiVec[2]", "HTSE.X_H1.XiVec[1]",
   "HTSE.AirTH.medium.T", "HTSE.FuelTH.medium.T"});
end dsmodelIterationSelect;
