model dsmodelIterationSelect
  extends NHES.Systems.BalanceOfPlant.Turbine.Examples.BOP_test_MSR;
  annotation(__Dymola_SimulationIterationVariables={"der(BOP.OFWH_2.medium.h)", 
  "mCA_Base_withBOP_sec_2_1.SHX.tube.flowModel.dps_fg[2]", "BOP.prt_b_steamdump.p",
   "der(BOP.SteamHeader.medium.p)", "der(BOP.SteamHeader.medium.h)", 
  "BOP.HPT.portHP.p", "BOP.HPT.state_a.h", "der(mCA_Base_withBOP_sec_2_1.SHX.tube.mediums[1].h)",
   "der(BOP.OFWH_1.medium.h)", "BOP.port_b_bypass.m_flow", "mCA_Base_withBOP_sec_2_1.PHX.tubeWall.port_b2[1].T",
   "mCA_Base_withBOP_sec_2_1.PHX.tubeWall.port_b2[2].T", "mCA_Base_withBOP_sec_2_1.PHX.tubeWall.port_b2[3].T",
   "mCA_Base_withBOP_sec_2_1.SHX.tubeWall.port_b2[1].T", "mCA_Base_withBOP_sec_2_1.SHX.tubeWall.port_b2[2].T",
   "mCA_Base_withBOP_sec_2_1.SHX.tubeWall.port_b2[3].T"});
end dsmodelIterationSelect;
