within NHES.Systems.BalanceOfPlant.Turbine.Examples;
model BOP_test_NTU_3
  extends Modelica.Icons.Example;
  parameter Real P_ext=138;
  parameter Real P_demand=1;
  parameter Modelica.Units.SI.Density d_ext= 42.55456924 "kg/m3";
  parameter Modelica.Units.SI.MassFlowRate m_ext=0;

     // booleanStep2(startTime=100000),
      //Steam_Extraction(y=data.m_ext),
  TRANSFORM.Fluid.BoundaryConditions.Boundary_pT steamdump(
    redeclare package Medium = Modelica.Media.Water.StandardWater,
    p=3400000,
    nPorts=1)
    annotation (Placement(transformation(extent={{0,74},{20,94}})));
  TRANSFORM.Electrical.Sources.FrequencySource boundary
    annotation (Placement(transformation(extent={{194,22},{174,42}})));
  NHES.Systems.BalanceOfPlant.Turbine.Data.Data_L3 data(
    HPT_p_in=12000000,
    p_dump=20000000,
    p_i1=2000000,
    p_i2=150000,
    cond_p=10000,
    Tin=813.15,
    Tfeed=473.15,
    d_HPT_in(displayUnit="kg/m3") = 34.69607167,
    d_LPT1_in(displayUnit="g/cm3") = 8.189928251,
    d_LPT2_in(displayUnit="kg/m3") = 0.862546399,
    mdot_total=288.5733428,
    mdot_fh=56.4311671,
    mdot_hpt=232.1421757,
    mdot_lpt1=232.1421757,
    mdot_lpt2=217.0235411,
    m_ext=m_ext,
    eta_t=0.9,
    eta_mech=0.99,
    eta_p=0.8)
    annotation (Placement(transformation(extent={{-100,82},{-80,102}})));

  Modelica.Blocks.Continuous.Integrator integrator
    annotation (Placement(transformation(extent={{170,66},{190,86}})));
  NHES.Electrical.PowerSensor sensorW
    annotation (Placement(transformation(extent={{140,42},{160,22}})));
  TRANSFORM.Fluid.BoundaryConditions.Boundary_pT bypassdump2(
    redeclare package Medium = Modelica.Media.Water.StandardWater,
    use_p_in=false,
    p=14000000,
    nPorts=1)
    annotation (Placement(transformation(extent={{-42,-18},{-22,2}})));
  PrimaryHeatSystem.MSR.Examples.MSR_NTU mSR_NTU
    annotation (Placement(transformation(extent={{-54,24},{-28,48}})));
  SteamTurbine_L3_HPOFWH_MSR_NTU steamTurbine_L3_HPOFWH_MSR_NTU(redeclare replaceable
                  NHES.Systems.BalanceOfPlant.Turbine.Data.Data_L3 data(
      Tin=813.15,
      Tfeed=473.15,
      d_HPT_in=34696.07167,
      d_LPT1_in=8189.928251,
      d_LPT2_in=862.546399,
      mdot_total=288.5733428,
      mdot_fh=1.128623343,
      mdot_hpt=287.4447195,
      mdot_lpt1=287.4447195,
      mdot_lpt2=268.7244172))
    annotation (Placement(transformation(extent={{60,-24},{112,24}})));
initial equation

equation

  connect(boundary.port, sensorW.port_b) annotation (Line(points={{174,32},{167,
          32},{167,32.2},{160,32.2}},
                             color={255,0,0}));
  connect(sensorW.W, integrator.u) annotation (Line(points={{150,41.4},{150,76},
          {168,76}},                   color={0,0,127}));
  connect(bypassdump2.ports[1], steamTurbine_L3_HPOFWH_MSR_NTU.port_b_bypass)
    annotation (Line(points={{-22,-8},{50,-8},{50,0},{60,0}}, color={0,127,255}));
  connect(mSR_NTU.port_b, steamTurbine_L3_HPOFWH_MSR_NTU.port_a_steam)
    annotation (Line(points={{4.76,40.08},{4.76,42},{50,42},{50,14.4},{60,14.4}},
                                                                         color=
          {0,127,255}));
  connect(mSR_NTU.port_a, steamTurbine_L3_HPOFWH_MSR_NTU.port_b_feed)
    annotation (Line(points={{5.54,32.16},{5.54,-14.4},{60,-14.4}},color={0,127,
          255}));
  connect(steamdump.ports[1], steamTurbine_L3_HPOFWH_MSR_NTU.prt_b_steamdump)
    annotation (Line(points={{20,84},{52,84},{52,24},{60,24}}, color={0,127,255}));
  connect(sensorW.port_a, steamTurbine_L3_HPOFWH_MSR_NTU.port_a_elec)
    annotation (Line(points={{140,32},{122,32},{122,0},{112,0}}, color={255,0,0}));
  annotation (experiment(
      StopTime=10000000,
      Interval=500,
      __Dymola_Algorithm="Esdirk45a"), Documentation(info="<html>
<p>Test of Pebble_Bed_Three-Stage_Rankine. The simulation should experience transient where external electricity demand is oscilating and control valves are opening and closing corresponding to the required power demand. </p>
<p>The ThreeStaged Turbine BOP model contains four control elements: </p>
<p>1. maintaining steam (steam generator outlet) pressure by using TCV</p>
<p>2. controling amount of electricity generated by using LPTBV1</p>
<p>3. maintaining feedwater temperature by using LPTBV2</p>
<p>4. maintaining steam (steam generator outlet) temperature by controlling feedwater pump RPM</p>
</html>"),
    __Dymola_Commands(executeCall=Design.Experimentation.sweepParameter(
          Design.Internal.Records.ModelDependencySetup(
          Model=
            "NHES.Systems.PrimaryHeatSystem.HTGR.HTGR_Rankine.Examples.Rankine_HTGR_Test_AR",
          dependencyParameters={Design.Internal.Records.DependencyParameter(
            name="hTGR_PebbleBed_Primary_Loop.CS.const11.k", values=linspace(
            1e-05,
            1e-06,
            6))},
          VariablesToPlot={Design.Internal.Records.VariableToPlot(name=
            "hTGR_PebbleBed_Primary_Loop.CS.CR.y"),
            Design.Internal.Records.VariableToPlot(name=
            "hTGR_PebbleBed_Primary_Loop.core.Q_total.y"),
            Design.Internal.Records.VariableToPlot(name=
            "hTGR_PebbleBed_Primary_Loop.core.fuelModel[2].T_Fuel")},
          integrator=Design.Internal.Records.Integrator(
            startTime=0,
            stopTime=1004200,
            numberOfIntervals=0,
            outputInterval=10,
            method="Esdirk45a",
            tolerance=0.0001,
            fixedStepSize=0)))),
    __Dymola_experimentSetupOutput(events=false));
end BOP_test_NTU_3;
